server:
  port: 8081

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름 사용
    url: jdbc:mysql://localhost:3306/db_OInjo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 사용
    username: root
    password: 1234
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
      # thymeleaf cache 비활성화

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  # file
#  itemImgLocation: /Users/minwook/Documents/GitHub/OInjo_Shop/OInjo_Shop/src/main/resources/static/productImg
#  uploadPath: /Users/minwook/Documents/GitHub/OInjo_Shop/OInjo_Shop/src/main/resources/static/productImg


  # file
    itemImgLocation: D:/Project/OInjo_Shop/OInjo_Shop/src/main/resources/static/productImg
    uploadPath: file:///D:/Project/OInjo_Shop/OInjo_Shop/src/main/resources/static/productImg




  #OAuth2.0 설정
  security:
    oauth2:
      client:
        registration:
          naver:
            #가져올 정보
#            scope: 'nickname,email,gender,age,profile_image'
            scope: 'nickname,email'
            client-id: bZVmEKcz6PsWA2nH0jot
            client-name: Naver
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-secret: wMpZRkPhHb
          kakao:
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-id: cc2502e7f55a8f8e6c7b51cd16c698cc
            #가져올 정보
            scope: profile_nickname, account_email
            client-name: Kakao
            client-authentication-method: POST
        provider:
          kakao:
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
